# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{payments-pl}
  s.version = "0.4.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Micha\305\202 M\305\202o\305\272niak"]
  s.date = %q{2010-08-19}
  s.description = %q{Simple library for payments via platnosci.pl}
  s.email = %q{m.mlozniak@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardoc/checksums",
     ".yardoc/objects/Payments.dat",
     ".yardoc/objects/Payments/ENCODINGS.dat",
     ".yardoc/objects/Payments/ERRORS.dat",
     ".yardoc/objects/Payments/POS_TYPES.dat",
     ".yardoc/objects/Payments/Pos.dat",
     ".yardoc/objects/Payments/Pos/cancel_i.dat",
     ".yardoc/objects/Payments/Pos/confirm_i.dat",
     ".yardoc/objects/Payments/Pos/encoding_i.dat",
     ".yardoc/objects/Payments/Pos/encrypt_i.dat",
     ".yardoc/objects/Payments/Pos/get_i.dat",
     ".yardoc/objects/Payments/Pos/initialize_i.dat",
     ".yardoc/objects/Payments/Pos/key1_i.dat",
     ".yardoc/objects/Payments/Pos/key2_i.dat",
     ".yardoc/objects/Payments/Pos/new_transaction_i.dat",
     ".yardoc/objects/Payments/Pos/new_transaction_url_i.dat",
     ".yardoc/objects/Payments/Pos/parse_response_body_i.dat",
     ".yardoc/objects/Payments/Pos/path_for_i.dat",
     ".yardoc/objects/Payments/Pos/pos_auth_key_i.dat",
     ".yardoc/objects/Payments/Pos/pos_id_i.dat",
     ".yardoc/objects/Payments/Pos/prepare_data_i.dat",
     ".yardoc/objects/Payments/Pos/send_request_i.dat",
     ".yardoc/objects/Payments/Pos/type_i.dat",
     ".yardoc/objects/Payments/Pos/verify_i.dat",
     ".yardoc/objects/Payments/PosInvalid.dat",
     ".yardoc/objects/Payments/PosNotFound.dat",
     ".yardoc/objects/Payments/RequestFailed.dat",
     ".yardoc/objects/Payments/SignatureInvalid.dat",
     ".yardoc/objects/Payments/Transaction.dat",
     ".yardoc/objects/Payments/Transaction/column_c.dat",
     ".yardoc/objects/Payments/Transaction/columns_c.dat",
     ".yardoc/objects/Payments/Transaction/new_url_i.dat",
     ".yardoc/objects/Payments/Transaction/pos_i.dat",
     ".yardoc/objects/Payments/ViewHelpers.dat",
     ".yardoc/objects/Payments/ViewHelpers/transaction_hidden_fields_i.dat",
     ".yardoc/objects/Payments/_40_40pos_table.dat",
     ".yardoc/objects/Payments/_5B_5D_c.dat",
     ".yardoc/objects/Payments/error_text_c.dat",
     ".yardoc/objects/Payments/get_pos_by_id_c.dat",
     ".yardoc/objects/Payments/get_pos_by_name_c.dat",
     ".yardoc/objects/Payments/init_c.dat",
     ".yardoc/objects/root.dat",
     ".yardoc/proxy_types",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/Payments.html",
     "doc/Payments/Pos.html",
     "doc/Payments/PosInvalid.html",
     "doc/Payments/PosNotFound.html",
     "doc/Payments/RequestFailed.html",
     "doc/Payments/SignatureInvalid.html",
     "doc/Payments/Transaction.html",
     "doc/Payments/ViewHelpers.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/frames.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "lib/payments/pos.rb",
     "lib/payments/transaction.rb",
     "lib/payments/view_helpers.rb",
     "lib/payments_pl.rb",
     "payments-pl.gemspec"
  ]
  s.homepage = %q{http://github.com/ronin/payments-pl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple library for payments via platnosci.pl}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

