# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{payments-pl}
  s.version = "0.4.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Micha\305\202 M\305\202o\305\272niak"]
  s.date = %q{2010-08-17}
  s.description = %q{Simple library for payments via platnosci.pl}
  s.email = %q{m.mlozniak@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "doc/Payments.html",
     "doc/Payments/Pos.html",
     "doc/Payments/PosNotFound.html",
     "doc/Payments/RequestFailed.html",
     "doc/Payments/SignatureInvalid.html",
     "doc/Payments/Transaction.html",
     "doc/Payments/ViewHelpers.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/frames.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "lib/payments/pos.rb",
     "lib/payments/transaction.rb",
     "lib/payments/view_helpers.rb",
     "lib/payments_pl.rb",
     "payments-pl.gemspec"
  ]
  s.homepage = %q{http://github.com/ronin/payments-pl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple library for payments via platnosci.pl}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

